// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: CheckMateProto.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol CheckMateServiceClientInterface: Sendable {

    @discardableResult
    func `greet`(request: GreetRequestProto, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<GreetResponseProto>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `greet`(request: GreetRequestProto, headers: Connect.Headers) async -> ResponseMessage<GreetResponseProto>
}

/// Concrete implementation of `CheckMateServiceClientInterface`.
public final class CheckMateServiceClient: CheckMateServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `greet`(request: GreetRequestProto, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<GreetResponseProto>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/CheckMateService/Greet", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `greet`(request: GreetRequestProto, headers: Connect.Headers = [:]) async -> ResponseMessage<GreetResponseProto> {
        return await self.client.unary(path: "/CheckMateService/Greet", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let greet = Connect.MethodSpec(name: "Greet", service: "CheckMateService", type: .unary)
        }
    }
}
