import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type ParsedSkill = {
  readonly id: string;
  readonly sourcePath: string;
  readonly workspacePath: string;
  readonly frontmatter: Record<string, string>;
  readonly body: string;
  readonly content: string;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(packageRoot, "..", "..");
const skillsDir = path.join(repoRoot, "skills");
const outputPath = path.join(
  packageRoot,
  "src",
  "agent",
  "generated",
  "sparkAgentSkills.generated.ts",
);

const skillOrder = [
  "paper-to-sheet",
  "handwritten-answers-to-sheet",
  "source-image-cropping",
  "gap-finder",
] as const;

function parseFrontmatter(
  content: string,
  filename: string,
): {
  frontmatter: Record<string, string>;
  body: string;
} {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/u.exec(content);
  if (!match) {
    throw new Error(`${filename} is missing YAML frontmatter.`);
  }

  const frontmatter: Record<string, string> = {};
  for (const rawLine of match[1]!.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith("#")) {
      continue;
    }
    const separatorIndex = line.indexOf(":");
    if (separatorIndex <= 0) {
      throw new Error(
        `${filename} has unsupported frontmatter line: ${rawLine}`,
      );
    }
    const key = line.slice(0, separatorIndex).trim();
    const rawValue = line.slice(separatorIndex + 1).trim();
    frontmatter[key] = rawValue.replace(/^["']|["']$/gu, "");
  }

  if (!frontmatter.name || !frontmatter.description) {
    throw new Error(
      `${filename} must define frontmatter name and description.`,
    );
  }

  return {
    frontmatter,
    body: content.slice(match[0].length).trimStart(),
  };
}

function assertSkillId(value: string): string {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(value)) {
    throw new Error(`Invalid skill name "${value}". Use lowercase kebab-case.`);
  }
  return value;
}

async function loadSkills(): Promise<ParsedSkill[]> {
  const entries = await readdir(skillsDir, { withFileTypes: true });
  const skills: ParsedSkill[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }
    const absolutePath = path.join(skillsDir, entry.name, "SKILL.md");
    const raw = await readFile(absolutePath, { encoding: "utf8" });
    const content = raw.trimEnd().concat("\n");
    const { frontmatter, body } = parseFrontmatter(
      content,
      `${entry.name}/SKILL.md`,
    );
    const id = assertSkillId(frontmatter.name!);
    if (entry.name !== id) {
      throw new Error(
        `${entry.name}/SKILL.md frontmatter name must match its directory.`,
      );
    }
    skills.push({
      id,
      sourcePath: path
        .relative(repoRoot, absolutePath)
        .split(path.sep)
        .join("/"),
      workspacePath: `skills/${id}/SKILL.md`,
      frontmatter,
      body: body.trimEnd().concat("\n"),
      content,
    });
  }

  const order = new Map(skillOrder.map((id, index) => [id, index]));
  skills.sort((left, right) => {
    const leftOrder = order.get(left.id) ?? Number.MAX_SAFE_INTEGER;
    const rightOrder = order.get(right.id) ?? Number.MAX_SAFE_INTEGER;
    if (leftOrder !== rightOrder) {
      return leftOrder - rightOrder;
    }
    return left.id.localeCompare(right.id);
  });

  return skills;
}

function indent(text: string, spaces: number): string {
  const prefix = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n");
}

function renderSkill(skill: ParsedSkill): string {
  return indent(
    JSON.stringify(
      {
        id: skill.id,
        name: skill.frontmatter.name,
        description: skill.frontmatter.description,
        sourcePath: skill.sourcePath,
        workspacePath: skill.workspacePath,
        frontmatter: skill.frontmatter,
        body: skill.body,
        content: skill.content,
      },
      null,
      2,
    ),
    2,
  );
}

async function main(): Promise<void> {
  const skills = await loadSkills();
  if (skills.length === 0) {
    throw new Error(`No skills/<name>/SKILL.md files found in ${skillsDir}`);
  }

  const union = skills.map((skill) => JSON.stringify(skill.id)).join(" | ");
  const file = [
    "// This file is generated by packages/llm/scripts/generate-agent-skills.ts.",
    "// Edit repo-root skills/*/SKILL.md, then run `bun run generate:agent-skills`.",
    "",
    `export type GeneratedSparkAgentSkillId = ${union};`,
    "",
    "export type GeneratedSparkAgentSkill = {",
    "  readonly id: GeneratedSparkAgentSkillId;",
    "  readonly name: string;",
    "  readonly description: string;",
    "  readonly sourcePath: string;",
    "  readonly workspacePath: `skills/${string}/SKILL.md`;",
    "  readonly frontmatter: Readonly<Record<string, string>>;",
    "  readonly body: string;",
    "  readonly content: string;",
    "};",
    "",
    "export const GENERATED_SPARK_AGENT_SKILLS = [",
    skills.map(renderSkill).join(",\n"),
    "] as const satisfies readonly GeneratedSparkAgentSkill[];",
    "",
  ].join("\n");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, file, { encoding: "utf8" });
}

await main();
