import {
  renderSparkAgentSkillReadList,
  SPARK_GRADER_SKILL_IDS,
} from "./sparkAgentSkills";

export const SPARK_GRADER_SUMMARY_PATH =
  "grader/output/run-summary.json" as const;
export const SPARK_GRADER_SHEET_PATH = "grader/output/sheet.json" as const;
export const SPARK_GRADER_UPLOADS_MANIFEST_PATH =
  "grader/uploads/index.json" as const;

export function buildSparkGraderAgentPrompt(options?: {
  summaryPath?: string;
  sheetPath?: string;
}): string {
  const summaryPath = options?.summaryPath ?? SPARK_GRADER_SUMMARY_PATH;
  const sheetPath = options?.sheetPath ?? SPARK_GRADER_SHEET_PATH;
  return [
    "Grade and process student uploaded work and related documents such as problem statements and official solutions.",
    "",
    "Read and follow these files first:",
    "- brief.md",
    "- request.json",
    "- grader/task.md",
    `- ${SPARK_GRADER_UPLOADS_MANIFEST_PATH}`,
    "",
    "Read and follow the reusable skills that match the chosen grader mode before grading. For ordinary handwritten grading against uploaded source/reference PDFs, read `paper-to-sheet` and `handwritten-answers-to-sheet`; read `source-image-cropping` only before actual crop work.",
    renderSparkAgentSkillReadList(SPARK_GRADER_SKILL_IDS),
    "",
    "Run-specific constraints:",
    "- Respect request.json input.referenceSourcePolicy for online-search permissions.",
    "- When official references are allowed and the paper/competition is identifiable, make a solid official-source lookup effort before self-solving: check official question paper/source and mark scheme/official solutions. Check examiner reports or grade-boundary/prize/medal thresholds only when the user explicitly asks for those external references.",
    "- Map the worksheet subject to Spark's stable Apple-style sheet palette and use that palette for `sheet.color`, `sheet.accent`, `sheet.light`, and `sheet.border`: Biology green; Mathematics blue; Chemistry purple; Physics indigo; Geography teal; Science mint; English pink; History or Religious Studies orange; Economics or Business yellow; Computer Science or General gray. Do not invent custom sheet colors.",
    "- Use `list_workspace_dir`, `read_workspace_file`, and `grep_workspace_files` for workspace text files. Use `write_workspace_file` for Markdown/text artifacts and `write_json_workspace_file` for grader JSON artifacts. Do not use `extract_text` to read JSON/Markdown workspace files.",
    "- The workspace and PDF tools are available in this run. Do not say you cannot access the local PDF or ask the user to upload it again until you have tried workspace-relative paths from `grader/uploads/index.json` with `extract_text`, `extract_pdf_reference_text`, `extract_pdf_images`, and `pdf_to_images` as appropriate. Use `view_image` when it is exposed; otherwise use `extract_text` for transcription and the fresh visual helper tools for localized crop inspection.",
    "- After a large extracted reference returns only an outline or `content omitted`, do not repeat the same unbounded read. Use `grep_workspace_files`, then `read_workspace_file` with `startLine`/`lineCount`; if your tool call cannot send those fields, use `read_file` with `offset`/`limit` on the workspace-relative path.",
    "- For source PDFs with named figures/diagrams/photos, run `extract_pdf_images` before `pdf_to_images`. Use `pdf_to_images` only when embedded images are missing labels/context, the visual is vector/layout-sensitive, or you need page context for a table/crop. For every displayed PDF crop, also keep or create a full rendered source-page JPEG no larger than 1500px on either side for the image click target.",
    "- For source PDFs, pass explicit 1-based `pageNumbers` for every `pdf_to_images` call, chosen from the extracted reference headings or grep context. `pageNumbers` is a required top-level tool field; do not hide it in `outputDir` or render a medium/long source PDF all at once.",
    "- Do not look up grade boundaries or examiner reports unless the user explicitly asked for those external references. When the task is to grade visible student work from uploaded question paper / mark scheme files, use those uploads and finish the source-faithful sheet first; a single component paper normally cannot be converted into a full qualification grade.",
    "- Model answers for incorrect responses must come from the uploaded source paper and mark scheme when those files are present. Do not download optional worked-example/examiner-report PDFs or other enrichment before the source-faithful sheet is complete unless the user explicitly asked for them.",
    "- For every source item whose wording names a figure, diagram, graph, chart, option diagram, or text/numeric table, decide the visual/table handling before writing `sheet.json`. Do not use SVG in prompts or linked worksheet images. Use Markdown/LaTeX only for simple horizontal/vertical grids, boxed arrays, and text/number layouts; angles, geometry, 3D, graphs, charts, maps, photos, apparatus, option diagrams, and other complex visuals must use source-backed images. If the uploaded/source PDF has the pixels or table text, the visible worksheet must include a PDF crop or Markdown table near the source-faithful prompt. For uploaded photos/scans, use a JPEG source image with `#spark-bbox=left,top,right,bottom` viewport links instead of repeated crop files. Example: if `01.1` begins `Figure 1 shows...`, then Figure 1 is mandatory for `01.1`; do not write or think that `Figure 1 might not be necessary`. Do not decide that a named visual can be omitted because the mark scheme or student answer makes grading possible without it; source-fidelity requires the visible student sheet to preserve the source visual. Do not use a linked-original/source-PDF instruction for ordinary source-paper visuals unless a real render/crop or table-extraction attempt failed and the failure is recorded in `sheet-plan.md` plus the source-fidelity audit. Do not put named figures/tables or image links in `section.theory`; if shared root context contains a figure/table, put that context and crop/table in the first dependent question or group prompt. Do not invent bridge text such as `Figure 1 and Figure 2 are used in this question`, `planned as crop`, `shown in the source paper`, or `options shown as diagram labels`; visible prompts should be printed source wording plus the crop/table.",
    "- Preserve source command words verbatim. If the paper says `Explain the results.`, do not rewrite it as `Describe and explain the results.` If the paper prints model options only as a labelled figure, do not write `Options: A, B, C, D shown in Figure 2`, `Options shown as A, B, C, D in Figure 2`, or `Options A-D shown in Figure 2`; transcribe the printed figure label/stem and include a guarded crop. If the paper prints a displayed formula/equation, do not write `displayed formula shown for ...`; render the displayed formula as Markdown/LaTeX or include a crop. Figure/table labels are prompt content, not numbering: never set a group `displayNumber` to `Figure 2` or `Table 1` above children like `01.2`/`01.3`; render those children directly with full `displayNumber` and short `badgeLabel`, or use a real source root group.",
    "- After source transcription, immediately write `sheet-plan.md` with the included leaves, marks, visual/table placements, and scoring batches. Self-check the plan before scoring: Total source marks must equal the sum of question-section totals and the sum of listed answer-leaf marks; Total answer-bearing leaves must equal the listed leaves. For long handwritten papers, do not hand-score the paper or polish crops after this point until `score_answers_with_fresh_agent` has been called for all planned batches.",
    '- Treat focus phrases such as "first 4 paragraphs" as grading-focus guidance, not permission to omit other visible prompts/responses. Keep later visible numbered items in the transcript and sheet unless the request names question numbers to exclude; mark whether they affected a grade projection.',
    "- Keep upload inventory, workspace file reading, primary transcription, final grading synthesis, and worksheet assembly on the main agent. For long handwritten papers, `score_answers_with_fresh_agent` must score bounded root-question batches, and the main agent must read those outputs and own final totals/review.",
    "- Use bounded subagents only for official-reference lookup/verification when online lookup is allowed, for visual localization proposals that keep image inspection out of the main context, for `score_answers_with_fresh_agent` root-question scoring on long handwritten papers, or through `validate_source_fidelity_with_fresh_agent` for pre-publish source-fidelity audits that compare source pages/transcripts against the assembled sheet without grading or rewriting it.",
    "- Use `propose_crop_bbox_with_fresh_agent` for uncertain PDF crop bbox planning, `validate_crop_with_fresh_agent` for final PDF crop validation, and `review_run_progress_with_fresh_agent` when repeated tool loops suggest the run is on the wrong path. For uploaded photos/scans, do not run the PDF-style crop-refinement loop; use at most two simple `view_image` passes and record the chosen `#spark-bbox` viewport. When validating PDF crops, pass `expectedContent` with the exact printed/visible visual labels/axes/options/table cells and `duplicatedTextToExclude` for prompt/caption/table text rendered separately. Do not ask the reviewer to require inferred answers, mark-scheme facts, or labels/headings absent from the source visual. If an embedded official figure image includes related subpanels, apparatus side panels, or scale labels inside the same figure object, describe the whole visible figure in `expectedContent` instead of repeatedly cropping it away.",
    "- If a crop reviewer fails an otherwise complete source visual only because `expectedContent` named inferred or unprinted content, such as a group name, answer, placeholder, or heading absent from the figure, correct `expectedContent` and revalidate once instead of recropping.",
    "- Validate only final linked PDF crop assets. If a text/numeric table or formula can be source-faithfully rendered as Markdown or LaTeX from extracted text, render it instead of crop-chasing, but use LaTeX only for simple horizontal/vertical layouts. Uploaded-photo viewport links do not need `crop-validation.md`; record their source JPEG, bbox, and two-pass `view_image` check in the plan/source-fidelity notes. If one PDF crop correction still fails for the same visual, switch representation when possible or call `review_run_progress_with_fresh_agent` before any further crop loop.",
    "- Scratch inventory paths such as `grader/output/pdf-images/...` are not worksheet assets and must not be linked directly. If an extracted PDF image object is already the right final visual, call `crop_image` with `fullImage: true` and the exact planned final `outputPath` under `grader/output/assets/...`; the tool guards source-edge crops with a white border. For PDF figures, make the Markdown image target the guarded crop and the link target a full source-page JPEG under `grader/output/source-pages/...` no larger than 1500px on either side. For uploaded photos/scans, make the Markdown image target a JPEG source image with `#spark-bbox=left,top,right,bottom` and the link target the same image without the fragment. Do not create `-raw`, `-candidate`, `-draft`, or temp copies under `grader/output/assets`. In capped first-pass assembly, link the guarded final asset path in `sheet.json` before crop validation; validate and record `crop-validation.md` only after JSON preflight names no schema/placement blockers. If `pad_image` adds a border to a crop that already passed validation, do not call `validate_crop_with_fresh_agent` again just because of padding; record the final padded path in `crop-validation.md` and note the passed source validation. If the original validation failed only because all required content touched an edge, pad once and validate that padded asset only.",
    "- For handwritten-grading papers with more than 12 answer leaves or more than 30 marks, call `score_answers_with_fresh_agent` immediately after the minimal `sheet-plan.md` exists. Prefer 2-4 contiguous root/range batches that cover all answer leaves and issue all of them in one parallel tool turn; do not start with a subset and wait. Include focused source excerpts, student-answer excerpts, mark-scheme excerpts, and short text summaries of any figure/table needed for scoring. Do not score the whole paper in one long hidden reasoning pass and do not delay the helper for crop polishing.",
    "- `score_answers_with_fresh_agent` returns per-question results inline and may return concise `modelAnswer` text for wrong items. Use the returned results directly for `review.questions` and requested model-answer/reference text, including `teacher-review` when returned; do not spend turns rereading every scoring file, reopening images to regrade, or deriving separate model answers unless a named question is missing or a validation error points to that file.",
    "- In capped/performance replays, size elapsed-time checkpoints to the external supervisor cap. For the current 20-minute cap, launch scoring by about T+10, write first `sheet.json` by T+16, validate by T+18, and publish by T+19:30. If behind, skip optional polish/enrichment and move to the next required artifact or gate.",
    '- Keep artifacts moving: once required scoring helper calls return, create only planned final guarded PDF image assets and full-page JPEG click targets that are still missing; if no source image inventory/page render exists, do one bounded source-visual prep step (`extract_pdf_images` to `grader/output/pdf-images` or `pdf_to_images` for exact pages under `grader/output/rendered-pages`) before final `crop_image`/`pad_image`. For uploaded photos/scans, reuse or normalize one JPEG source image and add `#spark-bbox` viewport links rather than creating repeated crops. Batch all missing crop/pad calls in one parallel tool turn using the exact final paths from `sheet-plan.md`; never create `-raw`, `-candidate`, `-draft`, or temp asset paths that need promotion. Then immediately write `sheet.json` with `write_json_workspace_file`; when the sheet is valid the tool may derive `run-summary.json`, so the next non-repair tool call must be `validate_grader_artifacts({"requireSourceFidelityAudit": false})`, not another summary-text turn. Do not crop-validate, reread scoring files, regrade, or enrich before first-pass JSON. Fix named schema/crop/source-fidelity blockers and record `crop-validation.md` when linked PDF crops exist before any source-fidelity audit. Use `write_json_workspace_file` with `jsonText` containing the complete JSON object; never pass `{}` or search for schema examples. Preserve returned scores/statuses rather than resolving ambiguity yourself. Use `mcq` only for printed choice/tick-box items; `answers[id]` must be the option id, not its label/text. Every `mcq.options[]` entry must have a non-empty `label`: use the printed source label when present, otherwise assign stable visible letters such as `A`, `B`, `C` while keeping the printed choice wording in `text`. If the source asks for an open answer even with a figure, use `lines`. Use `fill` only for simple one- or two-blank lines with `prompt`, `blanks`, and `after`; use `cloze` for any `segments`/`blanks` question. For long handwritten grading, use `lines` for calculation or worked-method leaves unless you provide a valid `calc` question with both `inputLabel` and `unit`; never write a bare `type: "calc"`. On long handwritten papers, publish the first valid compact artifact before optional feedback polishing; omit optional model-answer/reference enrichment and grade-boundary commentary if it would delay validation or publish.',
    "- If a source-fidelity audit fails, patch all blocking issues for that page/root in one coherent pass and run at most one follow-up audit for that same scope. If it still fails, call `review_run_progress_with_fresh_agent` or stop with the concrete blocker instead of looping.",
    "- Do not use `generate_json`, `validate_json`, or `validate_schema` for grader artifacts. Write grader JSON with `write_json_workspace_file`, use `validate_grader_artifacts` for preflight, and let `publish_sheet` validate the final publish state.",
    "- Do not write `request.json`, `brief.md`, attachment metadata, planning JSON, answer lists, or process summaries into grader output JSON files.",
    '- Do not stop after extraction, page inspection, crop review, or writing draft files. The run is not complete until `publish_sheet({})` returns `status: "published"`.',
    "",
    "Deliverables:",
    "1) Write `grader/output/transcription.md` from a transcription-first extraction pass, then normalize all visible student work into numbered statements/sentences rather than a summary. When grading against a source paper, include a source-faithful `## Source problem-statement transcription` section even when source text came from deterministic PDF extraction; it must be printed wording page by page for included source items and shared context, not a compact audit or needed-for-grading summary.",
    `2) Write one worksheet report JSON file at ${sheetPath}. This file is the full graded report wrapper, not the bare sheet data: top-level keys are \`schemaVersion\`, \`sheet\`, \`answers\`, \`review\`, and optional \`references\`; \`schemaVersion\` is exactly \`1\`; \`sheet\` contains the renderable worksheet data; \`answers\` contains one captured student answer for every answer-bearing leaf question id; student answers do not belong inside question objects.`,
    `3) If ${summaryPath} is not derived by the sheet write tool, write it with this exact top-level shape: \`{ "totals": { "awardedMarks": number, "maxMarks": number }, "presentation": { "title": string, "subtitle": string, "summaryMarkdown": string, "footer": string }, "sheet": { "title": string, "filePath": "${sheetPath}" } }\`, plus optional paper metadata only when known; if you include \`year\`, write it as a string such as \`"2024"\`. Keep \`presentation.summaryMarkdown\` as the sheet-card body: one compact sentence or two short fragments, specific, and not repeating title, subject, level, marks, percentage, created date, or footer. Prefer official grade/prize/medal/percentile outcome when known and suitable; otherwise mention the single most useful score driver, common examiner mistake made/avoided, or concrete next learning target. Do not use generic lead-ins such as "This sheet", "The worksheet", "Graded", "Checked", or broad praise.`,
    `4) In ${summaryPath}, set \`sheet.filePath\` exactly to \`${sheetPath}\`; publish_sheet rejects summaries that omit this field or point at any other path`,
    '5) In `review`, include `score`, `label` formatted as `N/total`, `message`, `note` (use `""` if there is no general note), and `questions`; in every scored `review.questions[questionId]`, include `status`: use `"correct"` for full marks, `"incorrect"` for partial/zero/blank answers, and preserve `"teacher-review"` when the bounded scoring helper returns it for genuinely ambiguous visible evidence',
    "6) When official grade/prize/medal/boundary data applies, mention the real-world outcome and basis in the worksheet feedback/reference markdown and briefly in the run summary when useful; if unavailable, say so instead of inventing it",
    `7) Once transcription, official/source references, and the sheet plan exist, stop broad reference reading/searching, do not search for schema examples, and for long handwritten papers use \`score_answers_with_fresh_agent\` in 2-4 parallel root/range batches before writing ${sheetPath} plus ${summaryPath}. Use the helper's returned question/model-answer results directly, including \`teacher-review\`; do not reread every scoring file or regrade from images. Before source-fidelity audit, verify both JSON files with \`validate_grader_artifacts({\"requireSourceFidelityAudit\": false})\``,
    "8) For printed source papers, source photos, or PDF-derived worksheets, call `validate_source_fidelity_with_fresh_agent` before publishing; the tool writes per-scope records under `grader/output/source-fidelity-audits/` and refreshes aggregate `grader/output/source-fidelity-audit.md`. Split long material by source page or root question and pass the relevant source reference markdown plus rendered page image paths in `sourcePaths`. The audit checks only transfer fidelity: every visible answered/partial/blank item is represented, source wording is verbatim apart from minimal OCR cleanup, numbering/badges match, figures/tables/layout-critical structures are visible near the prompt, and answer evidence is attached to the right item. A named figure/table with no nearby crop/Markdown table is blocking when source pixels/table text are available. Fix blocking findings together and run at most one follow-up audit for the same page/root.",
    "9) Call publish_sheet({}) to validate and publish the worksheet artifact; if it fails, use the validation error as a diagnostic, repair the artifacts coherently, and retry only while you are fixing a new class of issue rather than repeating the same failed branch",
    "10) Do not send a normal final response before publishing. If you catch yourself about to answer the user, instead keep using tools, write the required files, call publish_sheet, then call done.",
  ].join("\n");
}
